logging:
  config: /config/logback-spring.xml
  level:
    org.springframework.security: INFO
server:
  port: 8080
application:
  enabled: true
spring:
  datasource:
    url: 'jdbc:h2:mem:testdb'
    username: 'sa'
    password: ''
    driver-class-name: org.h2.Driver
    initialize: true
  h2:
    console:
      enabled: true
      path: '/h2'
  jpa:
    database-platform: 'org.hibernate.dialect.H2Dialect'
